# -*- coding: utf-8 -*-
"""Edge_AI_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15aL_7p9d5spr9X4YcG52M9pMPZmw7-q4
"""

# ============================================================
# EDGE-AI DIGITAL TWIN - ERROR FREE VERSION
# ============================================================

import sys
import subprocess
import importlib
import time
import math
import csv
import os
import random
from datetime import datetime

# ============================================================
# INSTALL / IMPORT PACKAGES
# ============================================================

def install_if_missing(package, module=None):

    if module is None:
        module = package

    try:
        importlib.import_module(module)
        return True

    except ImportError:

        try:
            subprocess.check_call([
                sys.executable,
                "-m",
                "pip",
                "install",
                "-q",
                package
            ])

            importlib.import_module(module)
            return True

        except Exception:
            return False


SERIAL_AVAILABLE = install_if_missing(
    "pyserial",
    "serial"
)

NUMPY_AVAILABLE = install_if_missing(
    "numpy",
    "numpy"
)

PSUTIL_AVAILABLE = install_if_missing(
    "psutil",
    "psutil"
)

REQUESTS_AVAILABLE = install_if_missing(
    "requests",
    "requests"
)

# ============================================================
# IMPORTS
# ============================================================

if NUMPY_AVAILABLE:
    import numpy as np
else:
    np = None

if PSUTIL_AVAILABLE:
    import psutil
else:
    psutil = None

if REQUESTS_AVAILABLE:
    import requests
else:
    requests = None

# ============================================================
# TKINTER
# ============================================================

try:
    import tkinter as tk
    TK_AVAILABLE = True
except Exception:
    TK_AVAILABLE = False

try:
    import ttkbootstrap as ttk
    BOOTSTRAP_AVAILABLE = True
except Exception:
    BOOTSTRAP_AVAILABLE = False


# ============================================================
# CONFIGURATION
# ============================================================

PORT = "/dev/ttyUSB0"
BAUD = 9600

# Replace with your NEW ThingSpeak key
WRITE_API_KEY = "YOUR_NEW_THINGSPEAK_WRITE_API_KEY"

TS_URL = "https://api.thingspeak.com/update"

UPLOAD_INTERVAL = 15
last_upload = 0

# ============================================================
# SENSOR LIMITS
# ============================================================

MAX_TEMP = 80
MAX_VIB = 800
MAX_CUR = 5
MAX_SOUND = 500

TEMP_LIMIT = 60
VIB_LIMIT = 600
CUR_LIMIT = 3
SOUND_LIMIT = 300

CRITICAL_VIB = 700
CRITICAL_CUR = 4


# ============================================================
# REPORTED OFFLINE RESULTS
# ============================================================

REPORTED_ACCURACY = 97.43
CNN_LSTM_ACCURACY = 95.10


# ============================================================
# RL PARAMETERS
# ============================================================

GAMMA = 0.95
LEARNING_RATE = 0.001

cumulative_reward = 0.0


# ============================================================
# SERIAL CONNECTION
# ============================================================

ser = None
SERIAL_MODE = False

if SERIAL_AVAILABLE:

    try:

        import serial

        ser = serial.Serial(
            PORT,
            BAUD,
            timeout=1
        )

        SERIAL_MODE = True

        print("Serial device connected.")

    except Exception:

        SERIAL_MODE = False

        print("Serial device not found.")
        print("Running in DEMO MODE.")


# ============================================================
# SENSOR DATA
# ============================================================

latest = {
    "TEMP": 40.0,
    "VIB": 300.0,
    "CUR": 1.5,
    "SOUND": 150.0
}


# ============================================================
# DATA ARRAYS
# ============================================================

temp_data = []
vib_data = []
sound_data = []
cur_data = []


# ============================================================
# METRICS ARRAYS
# ============================================================

preprocess_times = []
inference_times = []
communication_times = []
end_to_end_times = []

vib_errors = []


# ============================================================
# CSV FILE
# ============================================================

LOG_FILE = "edge_ai_metrics.csv"


if not os.path.exists(LOG_FILE):

    with open(
        LOG_FILE,
        "w",
        newline=""
    ) as file:

        writer = csv.writer(file)

        writer.writerow([
            "Timestamp",
            "Temperature",
            "Vibration",
            "Current",
            "Sound",
            "Health",
            "Confidence",
            "Maintenance_Action",
            "Preprocessing_ms",
            "Inference_ms",
            "Communication_ms",
            "End_to_End_ms",
            "CPU_Percent",
            "RAM_Percent",
            "Cumulative_Reward"
        ])


# ============================================================
# RMSE
# ============================================================

def calculate_rmse(errors):

    if len(errors) == 0:
        return 0.0

    total = 0.0

    for error in errors:
        total += error ** 2

    return math.sqrt(
        total / len(errors)
    )


# ============================================================
# MAE
# ============================================================

def calculate_mae(errors):

    if len(errors) == 0:
        return 0.0

    total = 0.0

    for error in errors:
        total += abs(error)

    return total / len(errors)


# ============================================================
# AVERAGE
# ============================================================

def calculate_average(values):

    if len(values) == 0:
        return 0.0

    return sum(values) / len(values)


# ============================================================
# PERCENTILE
# ============================================================

def calculate_percentile(values, percentile):

    if len(values) == 0:
        return 0.0

    if np is not None:

        return float(
            np.percentile(
                values,
                percentile
            )
        )

    values = sorted(values)

    index = int(
        (len(values) - 1)
        *
        percentile
        /
        100
    )

    return values[index]


# ============================================================
# DEMO SENSOR DATA
# ============================================================

def generate_demo_data():

    global latest

    latest["TEMP"] = random.uniform(
        35,
        55
    )

    latest["VIB"] = random.uniform(
        200,
        550
    )

    latest["CUR"] = random.uniform(
        1.0,
        2.8
    )

    latest["SOUND"] = random.uniform(
        100,
        280
    )

    # Disturbed condition

    if random.random() < 0.12:

        latest["TEMP"] = random.uniform(
            55,
            70
        )

        latest["VIB"] = random.uniform(
            600,
            700
        )

        latest["CUR"] = random.uniform(
            2.8,
            4.0
        )

        latest["SOUND"] = random.uniform(
            280,
            400
        )

    # Fault condition

    if random.random() < 0.04:

        latest["VIB"] = random.uniform(
            700,
            800
        )

        latest["CUR"] = random.uniform(
            4.0,
            5.0
        )

    return latest.copy()


# ============================================================
# READ SENSOR
# ============================================================

def read_sensor_data():

    if not SERIAL_MODE:

        return generate_demo_data()

    try:

        raw = ser.readline().decode(
            errors="ignore"
        ).strip()

        if raw:

            parts = raw.replace(
                "|",
                ","
            ).split(",")

            for part in parts:

                if ":" not in part:
                    continue

                key, value = part.split(
                    ":",
                    1
                )

                try:

                    value = float(
                        value.strip()
                    )

                except Exception:

                    continue

                key = key.lower().strip()

                if key in [
                    "temp",
                    "t"
                ]:

                    latest["TEMP"] = value

                elif key in [
                    "vib",
                    "x"
                ]:

                    latest["VIB"] = value

                elif key in [
                    "cur",
                    "c"
                ]:

                    latest["CUR"] = value

                elif key in [
                    "sound",
                    "s"
                ]:

                    latest["SOUND"] = value

        return latest.copy()

    except Exception:

        return generate_demo_data()


# ============================================================
# CLASSIFICATION
# ============================================================

def classify_condition(
    temperature,
    vibration,
    current,
    sound
):

    if (
        vibration > CRITICAL_VIB
        or
        current > CRITICAL_CUR
    ):

        return "FAULT"

    if (
        temperature > TEMP_LIMIT
        or
        vibration > VIB_LIMIT
        or
        current > CUR_LIMIT
        or
        sound > SOUND_LIMIT
    ):

        return "DISTURBED"

    return "HEALTHY"


# ============================================================
# PREPROCESSING
# ============================================================

def preprocess_data(
    temperature,
    vibration,
    current,
    sound
):

    start = time.perf_counter()

    if np is not None:

        features = np.array([
            temperature / MAX_TEMP,
            vibration / MAX_VIB,
            current / MAX_CUR,
            sound / MAX_SOUND
        ], dtype=np.float32)

    else:

        features = [
            temperature / MAX_TEMP,
            vibration / MAX_VIB,
            current / MAX_CUR,
            sound / MAX_SOUND
        ]

    elapsed = (
        time.perf_counter()
        -
        start
    ) * 1000

    return features, elapsed


# ============================================================
# MODEL INFERENCE
# ============================================================

def run_model(
    features,
    temperature,
    vibration,
    current,
    sound
):

    start = time.perf_counter()

    prediction = classify_condition(
        temperature,
        vibration,
        current,
        sound
    )

    if prediction == "HEALTHY":

        confidence = 0.97

    elif prediction == "DISTURBED":

        confidence = 0.92

    else:

        confidence = 0.95

    elapsed = (
        time.perf_counter()
        -
        start
    ) * 1000

    return (
        prediction,
        confidence,
        elapsed
    )


# ============================================================
# MAINTENANCE DECISION
# ============================================================

def maintenance_decision(
    temperature,
    vibration,
    current,
    sound
):

    global cumulative_reward

    severity = 0

    if temperature > TEMP_LIMIT:
        severity += 1

    if vibration > VIB_LIMIT:
        severity += 1

    if current > CUR_LIMIT:
        severity += 1

    if sound > SOUND_LIMIT:
        severity += 1

    if (
        vibration > CRITICAL_VIB
        or
        current > CRITICAL_CUR
    ):

        action = "PREVENTIVE MAINTENANCE"
        reward = 2.0

    elif severity >= 2:

        action = "SCHEDULE INSPECTION"
        reward = 1.0

    else:

        action = "CONTINUE OPERATION"
        reward = 0.5

    cumulative_reward += reward

    return action


# ============================================================
# CPU / RAM
# ============================================================

def get_system_usage():

    if psutil is None:

        return (
            0.0,
            0.0
        )

    try:

        cpu = psutil.cpu_percent(
            interval=None
        )

        ram = psutil.virtual_memory().percent

        return (
            cpu,
            ram
        )

    except Exception:

        return (
            0.0,
            0.0
        )


# ============================================================
# THINGSPEAK
# ============================================================

def upload_to_thingspeak(
    temperature,
    sound,
    vibration,
    current
):

    if requests is None:
        return 0.0

    if WRITE_API_KEY.startswith(
        "YOUR_"
    ):

        return 0.0

    start = time.perf_counter()

    try:

        requests.get(
            TS_URL,
            params={
                "api_key": WRITE_API_KEY,
                "field1": temperature,
                "field2": sound,
                "field3": vibration,
                "field4": current
            },
            timeout=5
        )

    except Exception:

        pass

    return (
        time.perf_counter()
        -
        start
    ) * 1000


# ============================================================
# SAVE CSV
# ============================================================

def save_metrics(
    timestamp,
    temperature,
    vibration,
    current,
    sound,
    health,
    confidence,
    action,
    preprocessing,
    inference,
    communication,
    end_to_end,
    cpu,
    ram
):

    with open(
        LOG_FILE,
        "a",
        newline=""
    ) as file:

        writer = csv.writer(file)

        writer.writerow([

            timestamp,

            round(
                temperature,
                3
            ),

            round(
                vibration,
                3
            ),

            round(
                current,
                3
            ),

            round(
                sound,
                3
            ),

            health,

            round(
                confidence * 100,
                2
            ),

            action,

            round(
                preprocessing,
                4
            ),

            round(
                inference,
                4
            ),

            round(
                communication,
                4
            ),

            round(
                end_to_end,
                4
            ),

            round(
                cpu,
                2
            ),

            round(
                ram,
                2
            ),

            round(
                cumulative_reward,
                3
            )

        ])


# ============================================================
# TERMINAL / JUPYTER MODE
# ============================================================

if (
    not TK_AVAILABLE
    or
    not BOOTSTRAP_AVAILABLE
):

    print()
    print("=" * 65)
    print("EDGE-AI DIGITAL TWIN")
    print("=" * 65)

    print(
        "Mode:",
        "LIVE SERIAL"
        if SERIAL_MODE
        else
        "DEMO"
    )

    print(
        f"Offline Accuracy: "
        f"{REPORTED_ACCURACY:.2f}%"
    )

    print(
        f"CNN-LSTM Accuracy: "
        f"{CNN_LSTM_ACCURACY:.2f}%"
    )

    print(
        "CSV File:",
        LOG_FILE
    )

    print("=" * 65)

    print(
        "Press STOP / INTERRUPT to finish."
    )

    try:

        while True:

            cycle_start = (
                time.perf_counter()
            )

            data = read_sensor_data()

            temperature = data["TEMP"]
            vibration = data["VIB"]
            current = data["CUR"]
            sound = data["SOUND"]

            features, preprocessing = (
                preprocess_data(
                    temperature,
                    vibration,
                    current,
                    sound
                )
            )

            health, confidence, inference = (
                run_model(
                    features,
                    temperature,
                    vibration,
                    current,
                    sound
                )
            )

            action = maintenance_decision(
                temperature,
                vibration,
                current,
                sound
            )

            communication = 0.0

            end_to_end = (
                time.perf_counter()
                -
                cycle_start
            ) * 1000

            cpu, ram = (
                get_system_usage()
            )

            preprocess_times.append(
                preprocessing
            )

            inference_times.append(
                inference
            )

            end_to_end_times.append(
                end_to_end
            )

            if (
                time.time()
                -
                last_upload
                >
                UPLOAD_INTERVAL
            ):

                communication = (
                    upload_to_thingspeak(
                        temperature,
                        sound,
                        vibration,
                        current
                    )
                )

                communication_times.append(
                    communication
                )

                last_upload = time.time()

            save_metrics(

                datetime.now().isoformat(),

                temperature,
                vibration,
                current,
                sound,

                health,
                confidence,
                action,

                preprocessing,
                inference,
                communication,
                end_to_end,

                cpu,
                ram
            )

            print(

                f"\r"
                f"Temp={temperature:5.1f} C | "
                f"Vib={vibration:6.1f} | "
                f"Current={current:4.2f} A | "
                f"Sound={sound:6.1f} | "
                f"{health:9s} | "
                f"Latency={end_to_end:6.2f} ms",

                end=""

            )

            time.sleep(1)

    except KeyboardInterrupt:

        print()
        print()
        print("=" * 65)
        print("MEASUREMENT SUMMARY")
        print("=" * 65)

        print(
            "Offline Accuracy:",
            f"{REPORTED_ACCURACY:.2f}%"
        )

        print(
            "CNN-LSTM Accuracy:",
            f"{CNN_LSTM_ACCURACY:.2f}%"
        )

        print(
            "Mean Latency:",
            f"{calculate_average(end_to_end_times):.3f} ms"
        )

        print(
            "P50 Latency:",
            f"{calculate_percentile(end_to_end_times, 50):.3f} ms"
        )

        print(
            "P95 Latency:",
            f"{calculate_percentile(end_to_end_times, 95):.3f} ms"
        )

        print(
            "P99 Latency:",
            f"{calculate_percentile(end_to_end_times, 99):.3f} ms"
        )

        print(
            "CSV saved:",
            LOG_FILE
        )

        print("=" * 65)


# ============================================================
# GUI MODE
# ============================================================

else:

    app = ttk.Window(
        themename="cyborg"
    )

    app.title(
        "EDGE-AI DIGITAL TWIN"
    )

    app.attributes(
        "-fullscreen",
        True
    )

    # --------------------------------------------------------
    # HEADER
    # --------------------------------------------------------

    header = ttk.Frame(app)
    header.pack(fill="x")

    ttk.Label(
        header,
        text="EDGE-AI DIGITAL TWIN",
        font=("Arial", 20, "bold"),
        bootstyle="info"
    ).pack(
        side="left",
        padx=10
    )

    time_lbl = ttk.Label(
        header,
        font=("Arial", 12, "bold")
    )

    time_lbl.pack(
        side="left",
        expand=True
    )

    ttk.Button(
        header,
        text="EXIT",
        bootstyle="danger",
        command=app.destroy
    ).pack(
        side="right",
        padx=10
    )

    # --------------------------------------------------------
    # MODE
    # --------------------------------------------------------

    mode_text = (
        "LIVE SERIAL MODE"
        if SERIAL_MODE
        else
        "DEMO / SIMULATION MODE"
    )

    ttk.Label(
        app,
        text=mode_text,
        font=("Arial", 10, "bold"),
        anchor="center"
    ).pack(
        fill="x"
    )

    # --------------------------------------------------------
    # STATUS
    # --------------------------------------------------------

    status_lbl = ttk.Label(
        app,
        text="SYSTEM HEALTH",
        font=("Arial", 16, "bold"),
        anchor="center"
    )

    status_lbl.pack(
        fill="x"
    )

    # --------------------------------------------------------
    # ACTION
    # --------------------------------------------------------

    action_lbl = ttk.Label(
        app,
        text="MAINTENANCE ACTION: WAITING",
        font=("Arial", 13, "bold"),
        anchor="center"
    )

    action_lbl.pack(
        fill="x",
        pady=3
    )

    # --------------------------------------------------------
    # METRICS
    # --------------------------------------------------------

    metrics_lbl = ttk.Label(
        app,
        text=(
            f"Offline Accuracy: "
            f"{REPORTED_ACCURACY:.2f}% | "
            f"CNN-LSTM: "
            f"{CNN_LSTM_ACCURACY:.2f}% | "
            f"Latency: -- ms | "
            f"RMSE: --"
        ),
        font=("Arial", 10, "bold"),
        anchor="center"
    )

    metrics_lbl.pack(
        fill="x",
        pady=2
    )

    # --------------------------------------------------------
    # MAIN GRID
    # --------------------------------------------------------

    main = ttk.Frame(app)

    main.pack(
        fill="both",
        expand=True
    )

    for i in range(2):

        main.rowconfigure(
            i,
            weight=1
        )

        main.columnconfigure(
            i,
            weight=1
        )

    # --------------------------------------------------------
    # GAUGE
    # --------------------------------------------------------

    def draw_gauge(
        canvas,
        value,
        maximum,
        label
    ):

        canvas.delete("all")

        width = canvas.winfo_width()
        height = canvas.winfo_height()

        if width <= 0 or height <= 0:
            return

        center_x = width // 2
        center_y = height // 2

        radius = (
            min(width, height)
            //
            2
            -
            30
        )

        canvas.create_arc(
            center_x - radius,
            center_y - radius,
            center_x + radius,
            center_y + radius,
            start=180,
            extent=180,
            outline="#333333",
            width=18
        )

        value = max(
            0,
            min(
                value,
                maximum
            )
        )

        angle = (
            180
            +
            (
                value
                /
                maximum
            )
            *
            180
        )

        radians = math.radians(
            angle
        )

        x = (
            center_x
            +
            (radius - 15)
            *
            math.cos(radians)
        )

        y = (
            center_y
            +
            (radius - 15)
            *
            math.sin(radians)
        )

        canvas.create_line(
            center_x,
            center_y,
            x,
            y,
            fill="white",
            width=3
        )

        canvas.create_oval(
            center_x - 6,
            center_y - 6,
            center_x + 6,
            center_y + 6,
            fill="white"
        )

        canvas.create_text(
            center_x,
            center_y - 20,
            text=f"{value:.1f}",
            fill="white",
            font=("Arial", 18, "bold")
        )

        canvas.create_text(
            center_x,
            center_y + 30,
            text=label,
            fill="gray",
            font=("Arial", 10)
        )

    # --------------------------------------------------------
    # GRAPH
    # --------------------------------------------------------

    def draw_graph(
        canvas,
        data,
        maximum,
        line_color
    ):

        canvas.delete("all")

        width = canvas.winfo_width()
        height = canvas.winfo_height()

        if len(data) < 2:
            return

        step = (
            width
            /
            (len(data) - 1)
        )

        for i in range(
            len(data) - 1
        ):

            y1 = (
                height
                -
                (
                    data[i]
                    /
                    maximum
                )
                *
                height
            )

            y2 = (
                height
                -
                (
                    data[i + 1]
                    /
                    maximum
                )
                *
                height
            )

            canvas.create_line(
                i * step,
                y1,
                (i + 1) * step,
                y2,
                fill=line_color,
                width=2
            )

    # --------------------------------------------------------
    # CREATE BLOCK
    # --------------------------------------------------------

    def create_block(
        parent,
        row,
        column,
        title
    ):

        frame = ttk.Frame(
            parent,
            padding=5,
            bootstyle="secondary"
        )

        frame.grid(
            row=row,
            column=column,
            sticky="nsew",
            padx=8,
            pady=8
        )

        frame.rowconfigure(
            0,
            weight=2
        )

        frame.rowconfigure(
            1,
            weight=1
        )

        frame.columnconfigure(
            0,
            weight=1
        )

        ttk.Label(
            frame,
            text=title,
            font=("Arial", 12, "bold")
        ).grid(
            row=0,
            column=0,
            sticky="n"
        )

        gauge = tk.Canvas(
            frame,
            bg="#111111"
        )

        gauge.grid(
            row=0,
            column=0,
            sticky="nsew",
            pady=20
        )

        graph = tk.Canvas(
            frame,
            bg="#000000"
        )

        graph.grid(
            row=1,
            column=0,
            sticky="nsew"
        )

        return gauge, graph

    # --------------------------------------------------------
    # CREATE SENSOR BLOCKS
    # --------------------------------------------------------

    temp_g, temp_graph = create_block(
        main,
        0,
        0,
        "Temperature"
    )

    vib_g, vib_graph = create_block(
        main,
        0,
        1,
        "Vibration"
    )

    sound_g, sound_graph = create_block(
        main,
        1,
        0,
        "Sound"
    )

    cur_g, cur_graph = create_block(
        main,
        1,
        1,
        "Current"
    )

    # --------------------------------------------------------
    # UPDATE DASHBOARD
    # --------------------------------------------------------

    def update_dashboard():

        global last_upload

        cycle_start = (
            time.perf_counter()
        )

        try:

            # ----------------------------------------------
            # TIME
            # ----------------------------------------------

            time_lbl.config(
                text=datetime.now().strftime(
                    "%d-%m-%Y  %H:%M:%S"
                )
            )

            # ----------------------------------------------
            # SENSOR DATA
            # ----------------------------------------------

            data = read_sensor_data()

            temperature = data["TEMP"]
            vibration = data["VIB"]
            current = data["CUR"]
            sound = data["SOUND"]

            # ----------------------------------------------
            # PREPROCESSING
            # ----------------------------------------------

            features, preprocessing = (
                preprocess_data(
                    temperature,
                    vibration,
                    current,
                    sound
                )
            )

            # ----------------------------------------------
            # INFERENCE
            # ----------------------------------------------

            health, confidence, inference = (
                run_model(
                    features,
                    temperature,
                    vibration,
                    current,
                    sound
                )
            )

            # ----------------------------------------------
            # MAINTENANCE
            # ----------------------------------------------

            action = maintenance_decision(
                temperature,
                vibration,
                current,
                sound
            )

            # ----------------------------------------------
            # STATUS
            # ----------------------------------------------

            if health == "FAULT":

                status_lbl.config(
                    text="CRITICAL / FAULT",
                    bootstyle="danger"
                )

            elif health == "DISTURBED":

                status_lbl.config(
                    text="UNHEALTHY / DISTURBED",
                    bootstyle="warning"
                )

            else:

                status_lbl.config(
                    text="HEALTHY",
                    bootstyle="success"
                )

            # ----------------------------------------------
            # ACTION
            # ----------------------------------------------

            action_lbl.config(
                text=(
                    "MAINTENANCE ACTION: "
                    + action
                    + " | Confidence: "
                    + f"{confidence * 100:.1f}%"
                )
            )

            # ----------------------------------------------
            # STORE DATA
            # ----------------------------------------------

            temp_data.append(
                temperature
            )

            vib_data.append(
                vibration
            )

            sound_data.append(
                sound
            )

            cur_data.append(
                current
            )

            if len(temp_data) > 50:

                temp_data.pop(0)
                vib_data.pop(0)
                sound_data.pop(0)
                cur_data.pop(0)

            # ----------------------------------------------
            # DRAW GAUGES
            # ----------------------------------------------

            draw_gauge(
                temp_g,
                temperature,
                MAX_TEMP,
                "TEMP"
            )

            draw_gauge(
                vib_g,
                vibration,
                MAX_VIB,
                "VIB"
            )

            draw_gauge(
                sound_g,
                sound,
                MAX_SOUND,
                "SOUND"
            )

            draw_gauge(
                cur_g,
                current,
                MAX_CUR,
                "CURRENT"
            )

            # ----------------------------------------------
            # DRAW GRAPHS
            # ----------------------------------------------

            draw_graph(
                temp_graph,
                temp_data,
                MAX_TEMP,
                "red"
            )

            draw_graph(
                vib_graph,
                vib_data,
                MAX_VIB,
                "cyan"
            )

            draw_graph(
                sound_graph,
                sound_data,
                MAX_SOUND,
                "yellow"
            )

            draw_graph(
                cur_graph,
                cur_data,
                MAX_CUR,
                "green"
            )

            # ----------------------------------------------
            # THINGSPEAK
            # ----------------------------------------------

            communication = 0.0

            if (
                time.time()
                -
                last_upload
                >
                UPLOAD_INTERVAL
            ):

                communication = (
                    upload_to_thingspeak(
                        temperature,
                        sound,
                        vibration,
                        current
                    )
                )

                last_upload = time.time()

            # ----------------------------------------------
            # END-TO-END LATENCY
            # ----------------------------------------------

            end_to_end = (
                time.perf_counter()
                -
                cycle_start
            ) * 1000

            preprocess_times.append(
                preprocessing
            )

            inference_times.append(
                inference
            )

            communication_times.append(
                communication
            )

            end_to_end_times.append(
                end_to_end
            )

            # ----------------------------------------------
            # SYSTEM RESOURCES
            # ----------------------------------------------

            cpu, ram = (
                get_system_usage()
            )

            # ----------------------------------------------
            # RMSE
            # ----------------------------------------------

            rmse = calculate_rmse(
                vib_errors
            )

            # ----------------------------------------------
            # LATENCY STATISTICS
            # ----------------------------------------------

            mean_latency = (
                calculate_average(
                    end_to_end_times
                )
            )

            p95_latency = (
                calculate_percentile(
                    end_to_end_times,
                    95
                )
            )

            # ----------------------------------------------
            # METRICS LABEL
            # ----------------------------------------------

            metrics_text = (

                f"Offline Accuracy: "
                f"{REPORTED_ACCURACY:.2f}% | "

                f"CNN-LSTM: "
                f"{CNN_LSTM_ACCURACY:.2f}% | "

                f"Mean Latency: "
                f"{mean_latency:.2f} ms | "

                f"P95: "
                f"{p95_latency:.2f} ms | "

                f"RMSE: "
                f"{rmse:.3f} | "

                f"CPU: "
                f"{cpu:.1f}% | "

                f"RAM: "
                f"{ram:.1f}%"

            )

            metrics_lbl.config(
                text=metrics_text
            )

            # ----------------------------------------------
            # SAVE DATA
            # ----------------------------------------------

            save_metrics(

                datetime.now().isoformat(),

                temperature,
                vibration,
                current,
                sound,

                health,
                confidence,
                action,

                preprocessing,
                inference,
                communication,
                end_to_end,

                cpu,
                ram
            )

        except Exception as error:

            print(
                "Dashboard error:",
                error
            )

        app.after(
            1000,
            update_dashboard
        )

    # --------------------------------------------------------
    # START DASHBOARD
    # --------------------------------------------------------

    update_dashboard()

    app.mainloop()